name: p_core
description: passengers networking utils.
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:

  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_image_compress: ^1.1.0
  freezed_annotation: ^2.0.3
  reactive_forms: ^13.0.0
  dio: ^4.0.6
  rxdart: ^0.27.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11