name: customer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1
  animations: ^2.0.2
  awesome_dialog: ^2.2.1
  darq: ^1.1.1
  duration_picker: ^1.1.0+1
  duration: ^3.0.11
  easy_localization: ^3.0.1-dev
  editable_image: ^1.0.1
  expandable_page_view: ^1.0.13
  extended_image: ^6.0.2+1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_easyloading: ^3.0.5
  freezed_annotation: ^2.0.3
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  go_router: ^4.0.0
  map_location_picker: ^0.0.2
  google_maps_flutter: ^2.1.5
  image_cropper: ^2.0.3
  smooth_page_indicator: ^1.0.0+2
  shimmer: ^2.0.0
  simple_animations: ^4.0.2
  hive: ^2.1.0
  p_network:
    path: ../../packages/p_network
  p_design:
    path: ../../packages/p_design
  p_core:
    path: ../../packages/p_core
  p_bootstrap:
    path: ../../packages/p_bootstrap
  path_provider: ^2.0.9
  provider: ^6.0.2
  reactive_image_picker: ^0.10.0
  reactive_dropdown_search: ^0.9.0
  rxdart: ^0.27.3
  time_range_picker: ^2.1.0
  reactive_phone_form_field: ^0.6.0
  intl_phone_field: ^3.1.0
  infinite_scroll_pagination: ^3.1.0
  flutter_image_compress: ^1.1.0
  reactive_date_time_picker: ^0.4.0
  network_logger: ^1.0.1
  badges: ^2.0.2
  signalr_netcore: ^1.3.0
  flutter_sticky_header: ^0.6.3
  google_maps_place_picker_mb: ^2.0.0-mb.20
  bot_storage: 1.0.4

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.0.3+1
  flutter_launcher_icons: ^0.9.2


dependency_overrides:
  reactive_forms:
    git:
      url: git@github.com:Husssam12/reactive_forms.git
      ref: develop
  dio_refresh_bot:
    git:
      url: git@github.com:flutterbots/flutterbots.git
      path: packages/dio_refresh_bot
  duration_picker:
    git:
      url: git@github.com:mr7ssam/duration_picker.git
  bot_storage:
    git:
      url: git@github.com:flutterbots/flutterbots.git
      path: packages/bot_storage


flutter:
  uses-material-design: true


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "dev_assets/logo.png"
  adaptive_icon_background: "#060816"
  adaptive_icon_foreground: "dev_assets/adaptive_logo.png"