name: shop_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.1
  animations: ^2.0.2
  awesome_dialog: ^2.2.1
  darq: ^1.1.1
  duration_picker: ^1.1.0+1
  duration: ^3.0.11
  easy_localization: ^3.0.1-dev
  editable_image: ^1.0.1
  expandable_page_view: ^1.0.13
  extended_image: ^6.0.2+1
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_easyloading: ^3.0.3
  flutter_wizard: ^2.0.4
  freezed_annotation: ^2.0.3
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  go_router: ^3.1.0
  map_location_picker: ^0.0.2
  google_maps_flutter: ^2.1.5
  image_cropper: ^1.5.1
  smooth_page_indicator: ^1.0.0+2
  shimmer: ^2.0.0
  simple_animations: ^4.0.2
  hive: ^2.1.0
  p_network: ^0.0.1
  p_design: ^0.0.1
  p_core: ^0.0.1
  p_bootstrap: ^0.0.1
  path_provider: ^2.0.9
  provider: ^6.0.2
  reactive_image_picker: ^0.9.0
  reactive_dropdown_search: ^0.6.0
  rxdart: ^0.27.3
  time_range_picker: ^2.1.0
  reactive_phone_form_field: ^0.4.0
  intl_phone_field: ^3.1.0
  infinite_scroll_pagination: ^3.1.0
  flutter_image_compress: ^1.1.0


dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  freezed: ^2.0.3+1
  flutter_launcher_icons: ^0.9.2


dependency_overrides:
  reactive_forms:
    git:
      url: git@github.com:Husssam12/reactive_forms.git
      ref: develop
  flutter_wizard:
    git:
      url: https://github.com/Husssam12/flutter_wizard.git
  dio_refresh_bot:
    git:
      url: git@github.com:flutterbots/flutterbots.git
      path: packages/dio_refresh_bot


flutter:
  uses-material-design: true



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "dev_assets/logo.png"
  adaptive_icon_background: "#060816"
  adaptive_icon_foreground: "dev_assets/adaptive_logo.png"