name: shop_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.2
  darq: ^1.1.1
  easy_localization: ^3.0.1-dev
  editable_image: ^1.0.1
  expandable_page_view: ^1.0.13
  extended_image: ^6.0.2+1
  flutter_bloc: ^8.0.1
  flutter_easyloading: ^3.0.3
  flutter_wizard: ^2.0.4
  freezed_annotation: ^1.1.0
  flutter_svg: ^1.0.3
  go_router: ^3.0.7
  get_it: ^7.2.0
  smooth_page_indicator: ^1.0.0+2
  hive: ^2.1.0
  p_network:
    path: ../../packages/p_network
  p_design:
    path: ../../packages/p_design
  p_core:
    path: ../../packages/p_core
  p_bootstrap:
    path: ../../packages/p_bootstrap
  path_provider: ^2.0.9
  provider: ^6.0.2
  reactive_forms: ^11.0.1
  reactive_image_picker: ^0.8.1
  reactive_dropdown_search: ^0.6.0
  rxdart: ^0.27.3
  time_range_picker: ^2.1.0
  reactive_phone_form_field: ^0.3.0
  intl_phone_field: ^3.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.8
  freezed: ^1.1.1
  flutter_gen_runner: ^4.1.6

dependency_overrides:
  flutter_wizard:
    git:
      url: https://github.com/Husssam12/flutter_wizard.git

flutter:
  uses-material-design: true

  assets:
    - assets/Illustrations/full_page/
    - assets/Illustrations/start_page/
    - assets/Illustrations/small_illustration/
