name: p_design
description: passengers apps theme.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil:
    git: git://github.com/Husssam12/flutter_screenutil.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  fonts:
    - family: PIcons
      fonts:
        - asset: lib/src/fonts/PIcons.ttf
    - family: NotoKufiArabic
      fonts:
        - asset: lib/src/fonts/ar/NotoKufiArabic-Black.ttf
        - asset: lib/src/fonts/ar/NotoKufiArabic-Bold.ttf
        - asset: lib/src/fonts/ar/NotoKufiArabic-ExtraBold.ttf
        - asset: lib/src/fonts/ar/NotoKufiArabic-ExtraLight.ttf
        - asset: lib/src/fonts/ar/NotoKufiArabic-Light.ttf
        - asset: lib/src/fonts/ar/NotoKufiArabic-Medium.ttf
        - asset: lib/src/fonts/ar/NotoKufiArabic-Regular.ttf
        - asset: lib/src/fonts/ar/NotoKufiArabic-SemiBold.ttf
        - asset: lib/src/fonts/ar/NotoKufiArabic-Thin.ttf
    - family: LexendDeca
      fonts:
        - asset: lib/src/fonts/en/LexendDeca-Black.ttf
        - asset: lib/src/fonts/en/LexendDeca-Bold.ttf
        - asset: lib/src/fonts/en/LexendDeca-ExtraBold.ttf
        - asset: lib/src/fonts/en/LexendDeca-ExtraLight.ttf
        - asset: lib/src/fonts/en/LexendDeca-Light.ttf
        - asset: lib/src/fonts/en/LexendDeca-Medium.ttf
        - asset: lib/src/fonts/en/LexendDeca-Regular.ttf
        - asset: lib/src/fonts/en/LexendDeca-SemiBold.ttf
        - asset: lib/src/fonts/en/LexendDeca-Thin.ttf