name: p_network
description: passengers networking utils.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  dio_refresh_bot: ^1.0.2
  bot_storage: ^1.0.2
  p_core: ^0.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0